### ISSUE TITLE
Cannot publish Config

### ISSUE THREAD

**Issue by jefferose** [davesweb/laravel-bricklink-api#1]
Hi there:

I've just installed this package into my Laravel 8.83 (PHP 8.1) project and when I try to publish the config & service provider I get an error. I'm running this in Sail, so:

`sail artisan vendor:publish --provider="Davesweb\\LaravelBicklinkApi\\ServiceProvider"`

The error is 

> No publishable resources for tag [].

Any thoughts? i'm excited to get this integrated and see how it works.

**Comment by davesweb** [comment]
Hi,

Thanks for your  report. 

Sorry for the late reply. I was indeed able to reproduce that scenario. A workaround for now would be to just run the command as `sail artisan vendor:publish` and then choose `Davesweb\LaravelBricklinkApi\ServiceProvider` from the list. This will publish the config file.

I will add a fix to publish the file with a single command soon.

**Comment by davesweb** [comment]
I updated the package to use the tag system of publishing assets in the latest release (1.0.1 and 1.0.2). Please let me know if there are any more issues you discover. Thanks!
